### PR TITLE
Single session

### LINKED ISSUE #236: Back button inside a room navigates to session picker instead of room list
When NOT in single-room mode and the current screen is the timeline of a room...
The back button should navigate to the screen with the list of rooms.
Instead, it navigates to the session picker.

https://github.com/Automattic/chatrix/assets/550401/fcb365af-1b64-4bd6-99d0-87d08f29b0ec

### PR DESCRIPTION
**Pull request by psrpinto**
Fixes #236 #224 #200

This PR makes it so that the session picker is only shown when there is no session, so that users can click "Sign in". Once a session exists (user has logged-in), it will always automatically enter the existing session on page load. Additionally, when a session exists, "Back" buttons that would lead to the session picker will no longer be rendered.

This effectively makes it so that Chatrix is a single-session client.

## TODO

- [x] If multiple sessions are encountered, log out all but the last, then enter the remaining one (the last one)
- [x] When session picker would be rendered, automatically enter the previously-existing session, if there is one. If not, show session picker.
- [x] If it's single-room mode, remove "Back" button in the room
- [x] If it's not single-room mode, remove "Back" button in Room list.

## Screen recordings

https://github.com/Automattic/chatrix/assets/550401/3bc4fb7c-aef5-4ecb-81c5-b94607dbebfb

https://github.com/Automattic/chatrix/assets/550401/19ec12ec-1a1e-49f9-a9c4-7a875b8a0884

### CODE REVIEW

**Comment by akirk** [comment]
4. Log them all out but the most recent one.

What about this?

**Comment by psrpinto** [comment]
Sadly, it doesn't seem to be possible to know which session is the most recent. So I'll go with option 1.?

**Comment by akirk** [comment]
Don't they have ids? I'd go with the last in the list and log all the others out.

**Comment by psrpinto** [comment]
The id is a random alphanumeric string, it's not incremental. 

> I'd go with the last in the list and log all the others out.

Alright, going with this one.

**Comment by psrpinto** [comment]
The screen recording doesn't shown it, but only one of the sessions was kept, the other one was logged out.

**Comment by akirk** [comment]
Maybe it's my local setup but when I try to build this I get:
```
yarn run v1.22.21
$ tsc && yarn run init && vite build --config frontend/vite-app.ts --emptyOutDir && yarn run build:logout && yarn run build:iframe && yarn run build:block
frontend/iframe/viewmodels/RootViewModel.ts:219:44 - error TS2339: Property 'resolveRoomAlias' does not exist on type 'HomeServerApi'.

219         let response = await homeserverApi.resolveRoomAlias(roomIdOrAlias).response();
                                               ~~~~~~~~~~~~~~~~

frontend/iframe/views/SessionView.ts:17:39 - error TS2307: Cannot find module 'hydrogen-web/src/platform/web/ui/session/room/WorldReadableRoomView' or its corresponding type declarations.

17 import { WorldReadableRoomView } from "hydrogen-web/src/platform/web/ui/session/room/WorldReadableRoomView";
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors in 2 files.

Errors  Files
     1  frontend/iframe/viewmodels/RootViewModel.ts:219
     1  frontend/iframe/views/SessionView.ts:17
error Command failed with exit code 2.

```

**Comment by psrpinto** [comment]
Mmm, that's weird. The [build succeeded ](https://github.com/Automattic/chatrix/actions/runs/7047199660/job/19180550615) so must be something about your local setup indeed.

You could try:

```shell
rm -rf node_modules vendor
make
```

Hopefully that will fix it

**Comment by akirk** [comment]
Still the same problem. I just wanted to help and test but I suppose I need to leave it to others.

**Comment by psrpinto** [comment]
It's weird, it should just work, not sure what could be the culprit.

**Comment by psrpinto** [comment]
AFAICT, the session picker is now never shown. I added another screen recording that shows the login/logout flow.

**Comment by psrpinto** [comment]
Thanks for testing @ashfame! Merging.

**Pull request merged**
