### PR TITLE
Indent with tabs instead of spaces

### PR DESCRIPTION
**Pull request by psrpinto**

### CODE REVIEW

**Comment by psrpinto** [comment]
Found another little thing, z-index is a string, not a number.

**Comment by ashfame** [comment]
I noticed that too, but then I have always see a number in css code and [MDN also indicates its a number](https://developer.mozilla.org/en-US/docs/Web/CSS/z-index) unless the value is string, which is why browsers parse `"1"` to `1` internally, I think.

**Comment by psrpinto** [comment]
It's indeed an int, the IDE fooled me. I dropped the commit.

**Review by ashfame — APPROVED** [review]
Lets land it 👍

**Pull request merged**
